batch_size: 4
compression_ratio: 0.5
dropout: 0.1
embedding_dim: 768
epochs: 5
fractal_scaling_factor: 1.0
learning_rate: 0.0001
log_file: null
log_level: DEBUG
max_batch_size: 32
max_concurrent_hosts: 10
memory_cleanup_interval: 300.0
memory_max_age_seconds: 3600.0
memory_max_size: 100
memory_path: ./memory
model_checkpoint_dir: ./checkpoints
num_clusters: 4
num_workers: 4
pin_memory: true
rate_limit_requests: 1.0
request_timeout: 10
scale_factor: 1.0
search_k: 5
use_cuda: false
validate_ssl: true
vocab_size: 50257
wandb_entity: null
wandb_project: fractal-neural-network
weight_decay: 1.0e-05
